### ISSUE TITLE
Do you have a list of keywords?

### ISSUE THREAD

**Issue by keyjm** [Netease-AutoTest/robotframework-weblibrary#1]
Would appreciate if you can provide the list of keywords. Couldn't find anything

**Comment by lucyking** [comment]
@kunalmalviya  
You can manually find all the wrapped KWs in [_webkeywords.py](https://github.com/Netease-AutoTest/robotframework-weblibrary/blob/master/src/Selenium2Library/keywords/_webkeywords.py) . 
I’ll try to generate the readthedoc wiki page when finish the annoying paper.

**Comment by lucyking** [comment]
@kunalmalviya
At present you can manually find all the wrapped KWs in [_webkeywords.py](https://github.com/Netease-AutoTest/robotframework-weblibrary/blob/master/src/Selenium2Library/keywords/_webkeywords.py) .
We’ll try to generate the readthedoc wiki page sooner.
